"""
K-water ALIO 연구보고서 자동화 파이프라인 (Streamlit Cloud 배포 버전)
- Plan A (안정화된 경로 고정) + Plan B (수동 파싱 및 업로드 복구) 결합
"""
from __future__ import annotations

import io
import json
import os
import queue
import tempfile
import threading
import zipfile
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st

# [주의] 동일 폴더 내에 pipeline/ 패키지(crawler, preprocessor, classifier, utils)가 있어야 합니다.
from pipeline import crawler, preprocessor, classifier
from pipeline.utils import (
    count_csv_rows,
    count_files,
    ensure_dir,
    human_size,
    list_files,
    make_zip_bytes,
)

# ────────────────────────────────────────────────────────────
# 1. 페이지 설정 및 초기화
# ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Alio 보고서 파이프라인",
    page_icon="💧",
    layout="wide",
)

st.markdown("""
<style>
[data-testid="stAppViewContainer"] { background: #f0f4f8; }
.header-card {
    background: linear-gradient(135deg, #0a2540 0%, #1a3a5c 100%);
    border-radius: 16px;
    padding: 28px 36px;
    margin-bottom: 24px;
    color: white;
}
.header-card h1 { margin: 0; font-size: 1.8rem; font-weight: 700; }
.header-card p  { margin: 6px 0 0; color: #90caf9; font-size: 0.95rem; }
.log-box {
    background: #1e1e2e; color: #a6e3a1; font-family: 'Courier New', monospace;
    font-size: 0.82rem; padding: 16px; border-radius: 8px; max-height: 300px;
    overflow-y: auto; white-space: pre-wrap;
}
</style>
""", unsafe_allow_html=True)

def is_streamlit_cloud() -> bool:
    return bool(os.environ.get("STREAMLIT_SERVER_HEADLESS") or
                os.environ.get("HOSTNAME", "").startswith("streamlit-"))

def get_openai_key() -> str:
    try:
        if "OPENAI_API_KEY" in st.secrets:
            return str(st.secrets["OPENAI_API_KEY"])
    except Exception:
        pass
    return os.environ.get("OPENAI_API_KEY", "")

# 세션 내 작업 디렉토리 고정 (리런 시 유실 방지)
if "work_dir" not in st.session_state:
    if is_streamlit_cloud():
        st.session_state.work_dir = os.path.join(os.getcwd(), "data_workspace")
    else:
        st.session_state.work_dir = str(Path.cwd())
    os.makedirs(st.session_state.work_dir, exist_ok=True)

# 초기화 세션 보정
for key, default in {
    "log_crawl": "", "log_preprocess": "", "log_classify": "",
    "chat_history": [], "uploaded_metadata_df": None, "uploaded_classified_df": None
}.items():
    st.session_state.setdefault(key, default)

TODAY = datetime.now().strftime("%Y%m%d")

@st.cache_data
def load_org_list() -> list[str]:
    for path in ("data/org_list.json", "org_list.json"):
        p = Path(path)
        if p.exists():
            return json.loads(p.read_text(encoding="utf-8"))
    return ["한국수자원공사"]

ORG_LIST = load_org_list()


# ────────────────────────────────────────────────────────────
# 2. 사이드바 설정
# ────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ⚙️ 설정")
    st.markdown("---")
    default_idx = ORG_LIST.index("한국수자원공사") if "한국수자원공사" in ORG_LIST else 0
    org_name = st.selectbox("기관명 선택", options=ORG_LIST, index=default_idx)

    st.markdown("---")
    st.markdown("**경로 설정**")
    work_dir = st.text_input("작업 폴더", value=st.session_state.work_dir)
    st.session_state.work_dir = work_dir
    work_path = Path(work_dir)

    safe_org = org_name.strip().replace(" ", "_")
    download_dir = st.text_input("PDF 저장 폴더", value=str(work_path / f"downloads_{safe_org}_{TODAY}"))
    metadata_csv = st.text_input("메타데이터 CSV", value=str(work_path / f"2_extracted_metadata_{TODAY}.csv"))
    classified_csv = st.text_input("분류 결과 CSV", value=str(work_path / f"3_classified_reports_{TODAY}.csv"))

    st.session_state.download_dir = download_dir
    st.session_state.metadata_csv = metadata_csv
    st.session_state.classified_csv = classified_csv

    st.markdown("---")
    if is_streamlit_cloud():
        st.info("☁️ Streamlit Cloud 구동 중")
    else:
        st.success("💻 로컬 환경")

    st.markdown('<div style="margin-top:50px; font-size:0.75rem; color:gray;">generated by wjelly@kwater.or.kr</div>', unsafe_allow_html=True)


# ────────────────────────────────────────────────────────────
# 3. 메인 상단 헤더
# ────────────────────────────────────────────────────────────
st.markdown(f'<div class="header-card"><h1>💧 Alio 보고서 파이프라인</h1><p>대상: <b>{org_name}</b></p></div>', unsafe_allow_html=True)


# ────────────────────────────────────────────────────────────
# 4. 파이프라인 실행 스레드 함수
# ────────────────────────────────────────────────────────────
def run_with_progress(fn, *, label: str, spinner_text: str, log_area, progress_area, status_area, log_key: str):
    log_lines: list[str] = []
    log_q: queue.Queue = queue.Queue()
    state = {"progress": (0, 0, ""), "result": None, "error": None, "done": False}

    def on_log(line: str): log_q.put(("log", line))
    def on_progress(cur: int, total: int, msg: str): log_q.put(("progress", cur, total, msg))
    
    def worker():
        try: state["result"] = fn(on_log=on_log, on_progress=on_progress)
        except Exception as e: state["error"] = str(e)
        finally: state["done"] = True

    th = threading.Thread(target=worker, daemon=True)
    th.start()

    pbar = progress_area.progress(0, text=f"{spinner_text} 준비 중...")
    while not state["done"] or not log_q.empty():
        try: item = log_q.get(timeout=0.1)
        except queue.Empty: continue
        
        if item[0] == "log":
            log_lines.append(item[1])
            log_area.markdown('<div class="log-box">' + "\n".join(log_lines[-40:]) + '</div>', unsafe_allow_html=True)
        elif item[0] == "progress":
            _, cur, total, msg = item
            if total > 0: pbar.progress(min(cur / total, 1.0), text=f"{spinner_text} {cur}/{total} · {msg[:60]}")
            else: status_area.markdown(f"`{msg}`")

    th.join(timeout=1.0)
    pbar.progress(1.0, text=f"{label} 완료")
    st.session_state[log_key] = "\n".join(log_lines)
    
    if state["error"]: 
        st.error(f"{label} 오류: {state['error']}")
        return None
    return state["result"]


# ────────────────────────────────────────────────────────────
# 5. 파이프라인 제어 콘솔 (버튼)
# ────────────────────────────────────────────────────────────
st.markdown("### 🚀 파이프라인 제어 콘솔")
bc1, bc2, bc3, bc4 = st.columns(4)
run_crawl = bc1.button("▶ 크롤링 실행", use_container_width=True)
run_preproc = bc2.button("▶ 데이터 전처리 (PDF 파싱)", use_container_width=True)
run_classify = bc3.button("▶ AI 기술분류", use_container_width=True)
run_all = bc4.button("⚡ 엔드투엔드 전체 실행", use_container_width=True, type="primary")

log_area, progress_area, status_
